### PR TITLE
Debug tools

### PR DESCRIPTION
**Pull request by Ecoral360**
This branch aim was to implement an easy and expandable debug set of tools. All the code related to those tools is found in the flyable/debug directory. 
There is essentially 2 parts to this system 

#### 1. The debug flag system
- In main.py, there is now a new constant variable called ENABLED_DEBUG_FLAG where you put all the flags you want to enable during the compilation of the program.
- Inside the compiler, the programmer can add a call to the function _value_if_debug_ that takes a **normal value**, a **debug value** and a **debug flag**. At runtime, the function will return the **debug value** if the specified flag is enabled, else the **normal value**.

#### example
~~~py
ENABLED_DEBUG_FLAGS: list[DebugFlags] = [
    DebugFlags.SHOW_VISIT_AST,
    DebugFlags.SHOW_OUTPUT_BUILDER,
]
...
DebugFlags.enable_debug_flags(*ENABLED_DEBUG_FLAGS)
~~~

#### 2. The analysers
- An analyser extends a particular class and wraps some of its methods to allow a non-intrusive, non-modifying way of debugging the class.
- It is recommended to create a debug flag for each analyser and instentiate it inside a _value_if_debug_ function along side its non-debug counterpart

#### example
~~~py
self.__builder = value_if_debug(CodeBuilder(self), CodeBuilderAnalyser(self), DebugFlags.SHOW_OUTPUT_BUILDER)
~~~

### CODE REVIEW

**Comment by ALavallee** [comment]
Few things to ease the merge : 
- Remove the test files (nbody, byte in python and others)
- I'm not really sure about the CODE_BUILDER_IDS. Seems like a lot of code rewriting.
- Explain here a bit what is the purpose of the Debug for CodeBuilder. What is the output of that.

Also for future commits, try to have the indent tool working closely to the default PyCharm since all of this new jump lines make it harder to grasp the core of the merge.

**Comment by Ecoral360** [comment]
The CodeBuilderAnalyser allows us to see exacly what instructions are passed to the c++ layer with what values. It allows for micro inspections of what the compiler is doing. It's the most detail tool that we have currently to debug code. It's downside really is the shear amount of information it prints to the screen so, for now at least, it's really only useful on small code or when you know where an unwanted behavior is detected.

The CodeBuilderAnalyser is the reason why CODE_BUILDER_IDS is required. Without it, it's not possible (or I didn't find how) to know which methods in CodeBuilder are actually writing stuff to the writer. I moved it to code_builder_analyser.py where it is used so it wouldn't be cumbersome in the actual CodeBuilder tho.

I removed the CodeWriteAnalyser tho because it was really used nowhere in the code and it wasn't really usefull to see what is written to the c++ layer without context.

**Comment by ALavallee** [comment]
Oh I get what you're saying.

I personally was using debug code inside the C++ layer to get that information for debug so I never had a case for that. 

Can you remove de test.py too from the merge too. Most of us have a local test.py and I don't want to pulling from the main overwriting it or conflicting with it.

**Comment by Ecoral360** [comment]
I will, I tried to add it to the .gitignore but it doesn't seem to exclude it for some reason

**Pull request merged**
