### PR TITLE
Support __call__ special method

### PR DESCRIPTION
**Pull request by daytonjallen**

### CODE REVIEW

**Comment by ALavallee** [comment]
Two things we need to add I think :
- The __call__ of the instance is called too
- We use a protocol if there is one for calls (unsure)

**Comment by daytonjallen** [comment]
So when __call__ is implemented, `tp_call` on the class is set to this implementation. One way I could improve this is to get `tp_call` directly and invoke it instead of going through `generate_python_call`. What do you think? @ALavallee

**Comment by ALavallee** [comment]
@daytonjallen 

Yes but you have to also handle the case where tp_call will be null. They are not forced to implement the protocol. A typical case is a user defined class where it holds an implementation of call, it that case tp_call pointer is null I believe.

**Comment by daytonjallen** [comment]
> but you have to also handle the case where tp_call will be null

The code I added to handle the \_\_call\_\_ case already covers this. If there is no \_\_call\_\_ implementation then the parser throws an error. If there is an implementation of \_\_call\_\_ then tp_call is guaranteed to be set since it points to this implementation.

This is all just for \_\_call\_\_ on the instance. The other cases are already covered previously

**Comment by ALavallee** [comment]
'If there is an implementation of __call__ then tp_call is guaranteed to be set'

Are you 100% sure about that ? If that is the case then it's good to me :) !

**Comment by daytonjallen** [comment]
Yeah, so from the documentation tp_call is mapped directly to \_\_call\_\_ (https://docs.python.org/3/c-api/typeobj.html)

and the most recent implementation of `PyCallable_Check` actually only checks that tp_call is set but in the past would also check for \_\_call\_\_ on the instance 

```c
int
PyCallable_Check(PyObject *x)
{
    if (x == NULL)
        return 0;
    return Py_TYPE(x)->tp_call != NULL;
}
```

**Comment by ALavallee** [comment]
Perfect then ! :)
Good job !

**Pull request merged**
