### PR TITLE
A lot of type hinting and a test unit system

### PR DESCRIPTION
**Pull request by Ecoral360**

### CODE REVIEW

**Comment by ALavallee** [comment]
I'll review this. It's also seems to be related to #44 so I'll probably merge this one ASAP.

**Comment by ALavallee** [comment]
Quick question. In what case _get_type_common would get second type as  None ? Feel in this case we should just crash so we know something bad happened.

**Comment by Ecoral360** [comment]
the reduce function will only be able to pass one argument if there was only one type passed as argument in the function

**Comment by ALavallee** [comment]
Oh okay I just saw that you changed get_most_common_type to get multiles arguments yeah make sens now.

**Comment by Ecoral360** [comment]
Yeah my goal was to make it less confusing when someone wanted to call the function with multiple types haha

**Comment by ALavallee** [comment]
All right all looks good to me :D ! I'll merge this. I haven't tested the integration yet but in any case I won't break anything that works right now.

Thank you so much for your contributions !

**Comment by Ecoral360** [comment]
Also, I was wondering what is the purpose of the parameter data in the function?

**Comment by ALavallee** [comment]
It's for future features. Basically there is some cases where two different types can lead to a new type and is not object ( in the case of inheritance by example).

It's just not implemented yet.

**Comment by Ecoral360** [comment]
ohhh, makes sense! thank you :D

**Comment by ALavallee** [comment]
Thank you to you ! ;P

**Pull request merged**
